### ISSUE TITLE
A question about the C-GQA dataset

### ISSUE THREAD

**Issue by TIan1874** [ExplainableML/co-cge#1]
Hello, sorry to bother you!

I have a question about the C-GQA dataset. I know that this was split by your team based on the Stanford GQA dataset, thank you very much for that! In the paper “Learning Graph Embeddings for Compositional Zero-shot Learning ”, the C-GQA dataset contains 453 state labels and 870 object labels. However, in the paper "Learning Graph Embeddings for Open World Compositional Zero-Shot Learning", the C-GQA dataset contains 413 state labels and 674 object labels. I would like to know why this dataset produced such a change, and which dataset you suggest to conduct experiments with in subsequent research.

Looking forward to your reply!

**Comment by mancinimassimiliano** [comment]
Hi @TIan1874 and I apologize for the very late reply!

The change is due to some issues with the initially proposed split (i.e. see https://github.com/ExplainableML/czsl/issues/3). If you use C-GQA, please use the updated version (the one we tested on also for our Co-CGE paper).
